apiVersion: apps/vl
kind: Deployment
metadata :
  name: plateforms-depl
spec :
  replicas: 1
  selector:
    matchLabe1s:
      app: plateformservice
  template:
    metadata :
      labels :
        app: plateformservice
    spec:
      containers :


apiVersion: apps/v1
kind: Deployment
metadata:
  name: plateforms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plateformservice
  template:
    metadata:
      labels:
        app: plateformservice
    spec:
      containers:
      - name: plateformservice
        image: 3ala3ajla/plateformservice:latest